### ISSUE TITLE
Strange image and layout behavior.

### ISSUE THREAD

**Issue by Neogene** [chiahsien/CHTCollectionViewWaterfallLayout#106]
Hi, we are facing a strange behavior: 

we use two CHTCollectionViewWaterfallCell in the Storyboard, one of them uses an uiimageview, and both have different sizes.

The issue we are facing is some images aren't loaded, in other cases the size of the CHTCollectionViewWaterfallCell is not updated and uses the size of the other cell.

Inizialization:
      
    CHTCollectionViewWaterfallLayout *layout =
    (CHTCollectionViewWaterfallLayout *)self.collection.collectionViewLayout;
    layout.minimumColumnSpacing=10.0;
    layout.minimumInteritemSpacing=10.0;
    layout.itemRenderDirection=CHTCollectionViewWaterfallLayoutItemRenderDirectionLeftToRight;
        
Layout:
- (void)updateLayoutForOrientation:(UIInterfaceOrientation)orientation {
    CHTCollectionViewWaterfallLayout *layout =
    (CHTCollectionViewWaterfallLayout *)self.collection.collectionViewLayout;
    
    layout.columnCount =
    IS_IPAD?
     (UIInterfaceOrientationIsPortrait(orientation) ? 3 : 4):2;
}

- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView
                  cellForItemAtIndexPath:(NSIndexPath *)indexPath {
    CHTCollectionViewWaterfallCell* newCell = [collectionView dequeueReusableCellWithReuseIdentifier: img?@"searchcell":@"searchcellnoimg" forIndexPath:indexPath];
if (imgCheck) {
 UIImageView *im = [newCell viewWithTag:10];
 im.image = //some image with imageNamed:
}
return newCell;
}

- (CGSize)collectionView:(UICollectionView *)collectionView
                  layout:(UICollectionViewLayout *)collectionViewLayout
  sizeForItemAtIndexPath:(NSIndexPath *)indexPath{
    
    NSDictionary *info = [self.search objectAtIndex:indexPath.row];
    
    BOOL img = //check;
    return  CGSizeMake(283, img?440:170);
}

The size detection code is the same for both the methods, checking the existence of the image from an nsarray.

Image is set properly but seems a refresh error, we tried chaning uiimageview size and calling setneeddisplay etc.

Dragging below and going back causes the cell to be refreshed and the image displayed properly.

Regarding size the problem is also really strange.

 Any help appreciated.

Attahched images of missing loaded image

1st image: the second box in the second column isn't updated regarding size.
2nd image: box without image loaded, when scrolling and going back the image is displayed.

![schermata 2015-08-10 alle 22 21 15](https://cloud.githubusercontent.com/assets/2322707/9183212/2a15b0ea-3fae-11e5-9f1d-17ba0a8c8d76.png)
![schermata 2015-08-10 alle 22 21 05](https://cloud.githubusercontent.com/assets/2322707/9183213/2a722f00-3fae-11e5-9d67-2192558799b4.png)

**Comment by Neogene** [comment]
Here a log of layoutattributesforelementsinrect: which returns 

(column 1 element 0): frame = (254 0; 244 379); , but is displayed with the wrong size.
(column 2 element 0): frame = (254 389; 244 379);  same behavior correct size but wrong displayed size.

![schermata 2015-08-11 alle 08 09 46](https://cloud.githubusercontent.com/assets/2322707/9191344/6106f170-4000-11e5-8b4c-5f75611cc65b.png)

**Comment by chiahsien** [comment]
Do you use `CHTCollectionViewWaterfallCell`? This class is for demo purpose, don't use it in your project.

I don't know how you construct your collection view cell, maybe there's an imageview layout issue in it. You can try to:
- Check your cell class, and see if your imageview's layout is set up correctly in different condition.
- Create two different cell classes, one with imageview, and one without imageview.

**Comment by Neogene** [comment]
Ok sorry, my mistake i use BOOL img = [UIImage imageNamed:...] using from years the knowledge 0 = NO and other values are YES, but in this case it get a random value which sometimes is evaluated as NO/YES randomly! Closing because is not an issue ! Thank you for the support.
