### ISSUE TITLE
CHTCollectionElementKindSectionHeader

### ISSUE THREAD

**Issue by ZuYuanZhou** [chiahsien/CHTCollectionViewWaterfallLayout#114]
let CHTCollectionElementKindSectionHeader = "CHTCollectionElementKindSectionHeader"
let CHTCollectionElementKindSectionFooter = "CHTCollectionElementKindSectionFooter"

why not put then global? Outside of the class?

**Comment by chiahsien** [comment]
Sounds reasonable! Could you send me a pull request?
