### ISSUE TITLE
Bug in layoutAttributesForItemAtIndexPath

### ISSUE THREAD

**Issue by Yourney** [chiahsien/CHTCollectionViewWaterfallLayout#115]
current code:

    override func layoutAttributesForItemAtIndexPath(indexPath: NSIndexPath) -> UICollectionViewLayoutAttributes!{
        if indexPath.section >= self.sectionItemAttributes.count{
            return nil
        }
        if indexPath.item >= self.sectionItemAttributes.objectAtIndex(indexPath.section).count{
            return nil;
        }
        var list = self.sectionItemAttributes.objectAtIndex(indexPath.section) as NSArray
        return list.objectAtIndex(indexPath.item) as UICollectionViewLayoutAttributes
    }

In the line where the second count is tested, there is a problem:
        if indexPath.item >= self.sectionItemAttributes.objectAtIndex(indexPath.section).count

1) As sectionItemAttributes is an NSMutableArray, the compiler can't (or shouldn't be able to) tell what the contents is. So nobody knows if a 'count' property exists.
2) There is no count property, cos a UICollectionViewLayoutAttributes doesn't have that.

Changed the function to the following to make it more robust (and working propely)

    override func layoutAttributesForItemAtIndexPath(indexPath: NSIndexPath) -> UICollectionViewLayoutAttributes!{
        if indexPath.section >= self.sectionItemAttributes.count {
            return nil
        }
        var list = self.sectionItemAttributes.objectAtIndex(indexPath.section) as! NSArray
		
		if indexPath.item >= list.count {
			return nil;
		}
        return list.objectAtIndex(indexPath.item) as! UICollectionViewLayoutAttributes
    }

**Comment by chiahsien** [comment]
Nice catch! Could you send me a pull request?

**Comment by chiahsien** [comment]
Done
