### ISSUE TITLE
Can I have a section with different column count?

### ISSUE THREAD

**Issue by purplepeng** [chiahsien/CHTCollectionViewWaterfallLayout#116]
HI, I want to have a section like below.
![d6826b99-2ce9-4f3a-84e5-34c7afdb2916](https://cloud.githubusercontent.com/assets/3256113/10886263/279a9240-81bc-11e5-97e8-f4d798ff413d.png)
Can I have a section with different column count? top has one, and below has three. Thank you!

**Comment by chiahsien** [comment]
You can implement this delegate method.
`- (NSInteger)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout columnCountForSection:(NSInteger)section;`

**Comment by purplepeng** [comment]
I want to have one section have different column count, just like the photo above; a section have four items;top has one column,below has three column. I tried the delegate method `- (NSInteger)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout columnCountForSection:(NSInteger)section;`, it seems that a section can't have two different columns.

**Comment by chiahsien** [comment]
Okay I got you.
Then the answer is **NO**, you can't have different columns in same section.

**Comment by purplepeng** [comment]
OK, Thank you all the same!
