### ISSUE TITLE
Request: tvOS support

### ISSUE THREAD

**Issue by mikerz** [chiahsien/CHTCollectionViewWaterfallLayout#117]
Shouldn't be too much of a problem given that tvOS has the collection view

**Comment by chiahsien** [comment]
I haven't studied tvOS yet, would you like to send a PR?

**Comment by stevenbr91** [comment]
I would love tvOS too

**Comment by chiahsien** [comment]
Can anyone tell me if it works well in tvOS?
- It doesn't work in tvOS and I need to fix some codes. Or,
- It works, all I need to do is adding `tvOS` to podspec.

**Comment by stevenbr91** [comment]
CHTCollectionViewWaterfallLayout is fully working for tvos :+1: rebuild the swift+storyboard demo project for tvos having no problems at all.
