### ISSUE TITLE
Swift - EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by hhertogh** [chiahsien/CHTCollectionViewWaterfallLayout#119]
I am using CHTCollectionViewWaterfallLayout in a CollectionViewController.

I always get the following error:

Thread 1 : EXC_BAD_ACCESS
on [super prepareLayout]; in prepareLayout.

I can't get rid of it.

**Comment by zesicus** [comment]
Hi, how did you solved the problem, I did get the same error in iOS 10, Xcode 10.2.1.
