### ISSUE TITLE
Add title below photo

### ISSUE THREAD

**Issue by yamifr07** [chiahsien/CHTCollectionViewWaterfallLayout#122]
Hi, I want to display a label with the image's title below the image. How could implement it in swift?

**Comment by chiahsien** [comment]
1. Create your own collection view cell
2. Put imageView and label on cell's contentView

**Comment by GABHISEKBUNTY** [comment]
Its not working and the image is coming over the label.

**Comment by rlam3** [comment]
@GABHISEKBUNTY were you able to find a workaround?

**Comment by chiahsien** [comment]
@rlam3 what's your issue?
