### ISSUE TITLE
Getting crash when adding CHTCollectionViewWaterfallLayout.

### ISSUE THREAD

**Issue by farhansyed9** [chiahsien/CHTCollectionViewWaterfallLayout#124]
i have this in my viewDidLoad:
CHTCollectionViewWaterfallLayout *layout = [[CHTCollectionViewWaterfallLayout alloc] init];
    
    layout.sectionInset = UIEdgeInsetsMake(10, 0, 10, 0); //set spacing from edge of screen, 10px from each edge
    layout.minimumColumnSpacing = 0; // space between columns
    layout.minimumInteritemSpacing = 0; // space between rows
    layout.columnCount = 1;
    layout.headerHeight = 0;
    layout.footerHeight = 10;
    self.collectionView.collectionViewLayout = layout;

i get this crash: 

*** Assertion failure in -[UICollectionViewData layoutAttributesForSupplementaryElementOfKind:atIndexPath:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.30.14/UICollectionViewData.m:860
2016-02-25 14:03:45.926 Spree[4829:1173541] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'no UICollectionViewLayoutAttributes instance for -layoutAttributesForSupplementaryElementOfKind: UICollectionElementKindSectionFooter at path <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}'

**Comment by chiahsien** [comment]
Have you implemented the footer? 
https://github.com/chiahsien/CHTCollectionViewWaterfallLayout/blob/develop/Demo/Demo/ViewController.m#L120

**Comment by caraballoj** [comment]
Any solution to this @farhansyed9? Im running into the same issue.
