### ISSUE TITLE
Adding subviews to the collection view cell with Autolayout.

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [chiahsien/CHTCollectionViewWaterfallLayout#125]
Adding subviews to the collection view cell with Autolayout is resulting in error as the image is not following the constraints set in IB.

**Comment by chiahsien** [comment]
Sorry, but you must do something wrong. It works well with auto layout.

**Comment by GABHISEKBUNTY** [comment]
@chiahsien Okay can you please open this demo in which added some more subviews in the collection view cells with autolayout. Please can you have a check on that?

[CHTWaterfallSwiftDemo.zip](https://github.com/chiahsien/CHTCollectionViewWaterfallLayout/files/160810/CHTWaterfallSwiftDemo.zip)

**Comment by chiahsien** [comment]
@GABHISEKBUNTY 

There's one auto layout issue with your cell.
The bottom view in your cell has `height = 128` constraint with `priority = 1000`. 
So, let's assume that the calculated cell height is `140`, then the image height would be `140-128-6 (spacing between them) = 6`.
If the calculated cell height is lower (e.g., 120), then there will be ambiguous constraints.

#### So, solution ####

1. Lower the bottom view's height constraint's constant. Or,
2. Lower the bottom view's height constraint's priority.

**Comment by GABHISEKBUNTY** [comment]
@chiahsien Please kindly check this source code that I have sent you. I have did something by adding dynamic label & so I am able to display all but there is a small problem that the labels cannot calculate their content size as per the width of the cell. 

[pintrestLayout.zip](https://github.com/chiahsien/CHTCollectionViewWaterfallLayout/files/163211/pintrestLayout.zip)
