### ISSUE TITLE
A possible crash

### ISSUE THREAD

**Issue by madordie** [chiahsien/CHTCollectionViewWaterfallLayout#127]
In "UICollectionViewWaterfallLayout.m -> - (void)prepareLayout -> 216:  NSInteger numberOfSections = [self.collectionView numberOfSections];"
In some cases, it is possible to read out the cause of data errors
so
  NSInteger numberOfSections = [self.collectionView.dataSource numberOfSectionsInCollectionView:self.collectionView];

Is this safe?

**Comment by chiahsien** [comment]
Do you know why it happens?

**Comment by madordie** [comment]
This crash occurs only twice, the above is changed after normal. But after I changed again to restore normal again. First according to the SDK program to do, wait until this function line, system statistics to crash statistics on this issue, then study again. Thank you!

PS: When tableView data source update when it happens UI are updated if the data source is not isolated operation will result in a similar manner to obtain a data error, resulting in a crash. I thought it was the problem, so make such speculation.
