### ISSUE TITLE
Pod install does not work with latest version (0.9.3)

### ISSUE THREAD

**Issue by johanlunds** [chiahsien/CHTCollectionViewWaterfallLayout#129]
```
The platform of the target `Fishbrain` (iOS 8.0) is not compatible with `CHTCollectionViewWaterfallLayout (0.9.3)`, which does not support `ios`.
```

Temporary solution was to rollback to old version:

Lock CHTCollectionViewWaterfallLayout to 0.9.2 in `PodsLocal/FIBCollectionViewController/FIBCollectionViewController.podspec.json`

**Comment by mrhether** [comment]
+1

**Comment by master-nevi** [comment]
+1

**Comment by chiahsien** [comment]
Sorry for that, I'll try to figure out what's going on.
Meanwhile, you can stick to 0.9.2.

It'd be great if anyone can send me a fix, I'm not a podspec syntax expert. :dizzy_face:

**Comment by chiahsien** [comment]
I've updated a new version, could you guys give it a try and let me know the result?

**Comment by bogren** [comment]
@chiahsien Thanks! Issue solved ✅
