### ISSUE TITLE
Set CollectionviewCell Height & Widht As Per Image Size

### ISSUE THREAD

**Issue by rakasakinaka** [chiahsien/CHTCollectionViewWaterfallLayout#133]
I Want To Set Widht & Height as per my resulted image. In Your Example Cat1.jpg Has Portrait Ratio, So When I replace it with my Landscape image At that time it it has extra spaces at TOP & BOTTOM.
So, that i want to set height & width dynamically
I have attached screenshot below, In Which left sided first image seems with extra space in TOP & BOTTOM
![simulator screen shot 12-may-2016 11 52 34 am](https://cloud.githubusercontent.com/assets/19200033/15205827/2c60f8f6-1838-11e6-8d95-e36e9ac4f893.png)

**Comment by chiahsien** [comment]
All you need to do is to provide **actual** size for each image, then the cell size will be adjusted automatically.

**Comment by rakasakinaka** [comment]
At Where I Have To Provide Actual size.?
In Following Part You guys have given size **statically**

- (NSArray *)cellSizes {
    if (!_cellSizes) {
        _cellSizes = @[
                       [NSValue valueWithCGSize:CGSizeMake(400, 550)],
                       [NSValue valueWithCGSize:CGSizeMake(1000, 665)],
                       [NSValue valueWithCGSize:CGSizeMake(1024, 689)],
                       [NSValue valueWithCGSize:CGSizeMake(640, 427)]
                       ];
    }
    return _cellSizes;
}

**Comment by smoi** [comment]
I have the same issue.

For testing i'm setting

 func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAtIndexPath indexPath: NSIndexPath) -> CGSize {
        return CGSizeMake(100, 230)
    }

but the cell's height is something around 400, any clue?

**Comment by chiahsien** [comment]
Cell size changes dynamically (based on collection view's width, column count, and spacing), but its ratio is same as that you provide.
