### ISSUE TITLE
the cell not reuse when collectionView reloadSections

### ISSUE THREAD

**Issue by stevensgy** [chiahsien/CHTCollectionViewWaterfallLayout#143]
the cell not reuse when [collectionView reloadSections:...]

**Comment by chiahsien** [comment]
that's your fault.

**Comment by stevensgy** [comment]
What's wrong with me?

**Comment by chiahsien** [comment]
What this layout does is to calculate item's size and position, `reusing cell` is the thing between you and the system.
So, if the cell isn't reused, then there must be something wrong with your code. The layout does nothing with it.
