### ISSUE TITLE
how to set margin to collection view?

### ISSUE THREAD

**Issue by jimmyzzzzzzz** [chiahsien/CHTCollectionViewWaterfallLayout#147]
I can set column spacing for spacing between  columns, how can I set leading and trailing space to superview for the first and last column?

**Comment by everlof** [comment]
Use this: `@property (nonatomic, assign) UIEdgeInsets sectionInset;` to get that effect.

**Comment by jimmyzzzzzzz** [comment]
thanks, this works great!

**Comment by girish54321** [comment]
Thanks @everlof
