### ISSUE TITLE
when i use the swift version for a colloectionView with a header in storyboard when i scroll to the top the error comes below

### ISSUE THREAD

**Issue by Nododo** [chiahsien/CHTCollectionViewWaterfallLayout#150]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: key cannot be nil'

**Comment by vikht0r** [comment]
Can you share the code where you declare the header?

**Comment by Nododo** [comment]
it's my own problem, i declare the header without using CHTCollectionElementKindSectionHeader but use the system header kind, i think it is the reason.
