### ISSUE TITLE
⚠️The #116 is a new BUG !

### ISSUE THREAD

**Issue by madordie** [chiahsien/CHTCollectionViewWaterfallLayout#174]
#166 @rafaelcr @chiahsien 

I find   [header attributed](https://github.com/chiahsien/CHTCollectionViewWaterfallLayout/blob/develop/CHTCollectionViewWaterfallLayout.m#L286)  AND  [footer attributed](https://github.com/chiahsien/CHTCollectionViewWaterfallLayout/blob/develop/CHTCollectionViewWaterfallLayout.m#L357)  THED  [merge return attributed](https://github.com/chiahsien/CHTCollectionViewWaterfallLayout/blob/develop/CHTCollectionViewWaterfallLayout.m#L451)

so . header and footer  KEY == `[NSIndexPath indexPathForItem:0 inSection:section]`

The result is that the __footer__ will __MUST__ replace the __header__

**Comment by chiahsien** [comment]
Hi @madordie ,
Thanks for the information, but I don't have time to work on this.
Could you send a PR to fix this bug?

**Comment by rafaelcr** [comment]
@madordie I'm sorry, I don't fully understand your comment.

If you're saying that the footer and header must *not* replace each other when they have the same `indexPath`, then you could change the code so that it not only separates elements into different `NSDictionary`s by their `representedElementCategory` but also by their `representedElementKind`.

**Comment by madordie** [comment]
@rafaelcr 

My English is not very good, so I use this [Google Translate](https://translate.google.com/zhzh-en/en)
😂😂😂

------

## DEMO-CHT # 166BUG

Reproduce the BUG described in [#174](https://github.com/chiahsien/CHTCollectionViewWaterfallLayout/issues/174).

### The main steps

In the `UICollectionViewWaterfallLayout.m -> - (void) prepareLayout`, set` `NSIndexPath indexPathForItem: 0 inSection: section]`

In the `UICollectionViewWaterfallLayout.m -> - (NSArray *) layoutAttributesForElementsInRect: (CGRect) rect`, using the` NSDictionary` as the storage structure, use `attr`` NSIndexPath` as the `NSDictionary` key

So, when `UICollectionViewWaterfallLayout.m -> - (NSArray *) layoutAttributesForElementsInRect: (CGRect) rect` need to return both` header` and `footer` 'will appear. That is, `value1` in` dict` will be replaced by `value2`.

```oc
NSMutableDictionary * dict = [NSMutableDictionary dictionary];
Dict [@ "KEY"] = @ "value1";
Dict [@ "KEY"] = @ "value2";
```

I wrote a [demo](https://github.com/madordie/Demo-CHT-166BUG)

If it is my usage problem, we can discuss this issue together 😊

------

## DEMO-CHT#166BUG

重现[#174](https://github.com/chiahsien/CHTCollectionViewWaterfallLayout/issues/174)中所描述的BUG。

### 主要步骤

在 `UICollectionViewWaterfallLayout.m -> - (void)prepareLayout` 中，设置`header`、`footer`使用的`NSIndexPath`定义均为`[NSIndexPath indexPathForItem:0 inSection:section]`

在 `UICollectionViewWaterfallLayout.m -> - (NSArray *)layoutAttributesForElementsInRect:(CGRect)rect`中，采用了`NSDictionary`作为存储结构，使用`attr`的`NSIndexPath`作为`NSDictionary`的key

所以，当`UICollectionViewWaterfallLayout.m -> - (NSArray *)layoutAttributesForElementsInRect:(CGRect)rect`需要同时返回`header`和`footer`将会出现`header`被`footer`替换的现象。即：`dict`中的`value1`将被`value2`所替换。

``` oc
NSMutableDictionary *dict = [NSMutableDictionary dictionary];
dict[@"KEY"] = @"value1";
dict[@"KEY"] = @"value2";
```
我写了一个[demo](https://github.com/madordie/Demo-CHT-166BUG)

 如果是我的用法问题，我们可以一起在讨论一下这个问题😊

**Comment by ericwang24** [comment]
I got same error.  
My collection view have section header and footer, but only `CHTCollectionElementKindSectionFooter` passing in
`- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath`

**Comment by rafaelcr** [comment]
@madordie thanks, I just submitted a new PR and realized you made the exact same change 😝

**Comment by madordie** [comment]
😊

**Comment by madordie** [comment]
#179 

@chiahsien need update tag for cocoapods 😂

**Comment by chiahsien** [comment]
okay, new tag published!
