### ISSUE TITLE
Swift package manager support..

### ISSUE THREAD

**Issue by lvnkmn** [chiahsien/CHTCollectionViewWaterfallLayout#194]
..would be great!

**Comment by lvnkmn** [comment]
And I've implemented this in my for, I will create a pull request shortly.

**Comment by lvnkmn** [comment]
Super nice that this is merged. Looking forward to a release of this.

**Comment by lvnkmn** [comment]
@chiahsien,  can you create a release using this code? Until then SPM cannot be used with version numbers.

**Comment by chiahsien** [comment]
@lvnkmn Please send me the PR. I don’t do iOS for a while and i need support from community. 😃

**Comment by ApolloZhu** [comment]
@chiahsien I think only you as the project owner (or another collaborator who has the permission) can do this. You have created [releases on GitHub](https://github.com/chiahsien/CHTCollectionViewWaterfallLayout/releases) before (like [this one](https://github.com/chiahsien/CHTCollectionViewWaterfallLayout/releases/tag/0.9.7)). But just in case, [this](https://help.github.com/en/github/administering-a-repository/creating-releases) shows how you can create a new release

**Comment by lvnkmn** [comment]
@ApolloZhu is right.

To release a version for SPM, all you have to do is (considering the development branch is stable and contains everything that needs to be released). ->

1. Merge `development` into `master`
2. Tag it with  `0.10.0` considering there's no breaking changes or `1.0.0` when there's been breaking changes since last release.
3. Make sure you push the changes and tags.

**Comment by chiahsien** [comment]
I understand. But since this project is in maintenance mode, I think it'd be better to follow latest master branch instead of certain tag. 

I'm happy to merge PR into master, but I'm lazy to release a new tag and update CocoaPods/SPM, and sometimes it doesn't worth it to release a new tag for a minor patch.

How do you think? Any suggestions?

**Comment by lvnkmn** [comment]
Ok. What I could do, is cherry pick the SPM commit and create a PR which you can merge into master. 

In order to get some benefit out of this, is to tag this with a += 0.0.1 version so the new version would be ‘0.9.8’. 

Eventhough for github this would count as a release, there would be no added benefit of creating a cocoapods release for it, so you can skip that for this one. SPM users would be happy though. Every release after that would just work for SPM with no added work. 

Sounds reasonable?

**Comment by lvnkmn** [comment]
Or you could do the cherry pick into master + tag of course 🙂

**Comment by chiahsien** [comment]
I’ve pushed a new tag, please help to check if it works.

**Comment by lvnkmn** [comment]
Thanks. Will let you know. First thing tomorrow morning.

**Comment by lvnkmn** [comment]
It works for me. So far no issues. Will close this. Thanks for the work!
