### ISSUE TITLE
Construct Grid on the Fly?

### ISSUE THREAD

**Issue by donholly** [chiahsien/CHTCollectionViewWaterfallLayout#27]
I wanted to start a discussion on whether it would be possible to construct the layout on the fly, rather than all at once in `prepareLayout`.

The reason for this would be for very large data sets. There are times when I display nearly 50,000 cells in a collectionView and it takes a noticeable amount of time to do the height calculations `'heightForItemAtIndexPath`.

Instead, would it be possible to 'lazy load' the cell layoutAttributes as you're scrolling?

I'd be happy to take a stab at it, I just wanted to see if there was any concern in doing this.

Thanks!

**Comment by whytimber** [comment]
> I wanted to start a discussion on whether it would be possible to construct the layout on the fly, rather than all at once in `prepareLayout`.
> 
> The reason for this would be for very large data sets. There are times when I display nearly 50,000 cells in a collectionView and it takes a noticeable amount of time to do the height calculations `'heightForItemAtIndexPath`.
> 
> Instead, would it be possible to 'lazy load' the cell layoutAttributes as you're scrolling?
> 
> I'd be happy to take a stab at it, I just wanted to see if there was any concern in doing this.
> 
> Thanks!

Hello,Are you making any progress on this issue
