### ISSUE TITLE
Calling reloadData in cellForItemAtIndexPath method brings some strange behavior.

### ISSUE THREAD

**Issue by hovox** [chiahsien/CHTCollectionViewWaterfallLayout#5]
Calling reloadData in cellForItemAtIndexPath method most items, and cellForItemAtIndexPath is not called again.
Can't find out why but if calling reloadData with dispatch_async , then everything is ok.

Here is a code snippet , just change in viewcontroller this method:

BOOL reloaded = NO;
- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView
                cellForItemAtIndexPath:(NSIndexPath *)indexPath
  {
  UICollectionViewWaterfallCell *cell =
  (UICollectionViewWaterfallCell *)[collectionView dequeueReusableCellWithReuseIdentifier:CELL_IDENTIFIER
                                                                             forIndexPath:indexPath];
  
  cell.displayString = [NSString stringWithFormat:@"%d", indexPath.row];
  if (indexPath.row == CELL_COUNT - 2 && !reloaded) {
  
  ```
  reloaded = YES;
  ```
  
  //        dispatch_async(dispatch_get_main_queue(), ^{
          [self.collectionView reloadData];
  //        });
  }
  return cell;
  }

**Comment by reza-khalafi** [comment]
Add this to viewDidLoad:


    self.automaticallyAdjustsScrollViewInsets = NO;
