### ISSUE TITLE
Crash on data reload with 0 items and sections

### ISSUE THREAD

**Issue by natenash203** [chiahsien/CHTCollectionViewWaterfallLayout#76]
First off, great work on the layout. I use the layout for a couple sections with three or four items each. Each section has a header and the items are populated by data retrieved from a network call. I have a method that removes all objects from the data source and sets everything back to zero. For example, 0 sections, with 0 items. Essentially an empty array. The method looks a bit like this:

```
- (IBAction)resetButtonTapped:(id)sender
{
    [self.dataSource removeAllObjects];
    [self.collectionView reloadData];
}
```

Whenever I reset everything back to zero, and call reloadData, the following exception is thrown:

```
*** Assertion failure in -[UICollectionViewData layoutAttributesForSupplementaryElementOfKind:atIndexPath:], /SourceCache/UIKit_Sim/UIKit-3318/UICollectionViewData.m:853
2014-10-19 19:18:22.554 Hord[31192:4215382] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'request for layout attributes for supplementary view CHTCollectionElementKindSectionHeader in section 0 when there are only 0 sections in the collection view'
```

A similar issue was reported on another custom UICollectionViewLayout [here](https://github.com/monospacecollective/MSCollectionViewCalendarLayout/issues/7). However, the other layout appears to have some sort of cache invalidation logic built in.  

It looks like the layout object is still trying to return attributes for a header that no longer exists. Any advice you have on resolving this issue is much appreciated.  Thanks in advance!

**Comment by jefflen** [comment]
I'm experiencing this issue as well, but I solved this by never returns zero in the collection view data source,
```
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView *)collectionView
{
    NSInteger count = [self sectionTitles].count;
    return (count == 0) ? 1 : count;
}
```
 and then check and returns an supplementary view with empty contents,
```
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView
           viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath
{
    NSArray *sectionTitles = [self sectionTitles];
    
    MyCollectionHeaderView *headerView = [collectionView dequeueReusableSupplementaryViewOfKind:kind
                                                                            withReuseIdentifier:kind
                                                                                   forIndexPath:indexPath];
    
    if (sectionTitles.count == 0) {
        headerView.titleLabel.text = @"";
        return headerView;
    }
    else { 
        ...
    }
}
```
you may need to check for other data source methods as well for this modification.

**Comment by chiahsien** [comment]
Interesting. Can't `numberOfSectionsInCollectionView` return 0? I can't find any document addressing this, anyone?

**Comment by jefflen** [comment]
I tried to modify the ```CHTCollectionViewWaterfallLayout``` class without success so just use this patch method instead. Not sure why it won't works when return zero...

**Comment by dginsburg** [comment]
Fixed in PR #93

**Comment by chiahsien** [comment]
Thanks @dginsburg !

**Comment by hebinda** [comment]
self.floatingSectionIndex = -1;
Initialization of floatingSectionIndex is needed in prepareLayout. When search result filtered down sections, the current floating section doesn't exist anymore

**Comment by Isuru-Nanayakkara** [comment]
I'm getting this error in the Swift version.

**Comment by satashiabhavin** [comment]
deinit {
        SDWebImageDownloader.shared.cancelAllDownloads()
    }
