### ISSUE TITLE
making the section headers float

### ISSUE THREAD

**Issue by guyisra** [chiahsien/CHTCollectionViewWaterfallLayout#85]
I realize that this may be beyond the scope of the purpose of this project, but assuming that I have another custom layout that takes care of making sure that the headers float.

since CHTCollectionViewWaterfallLayout and MyFloatyLayout use the same functions (namely layoutAttributesForElementsInRect) How can I combine the two, while keeping the use of CHTCollectionViewWaterfallLayout?

**Comment by chiahsien** [comment]
Sorry, I can't get you. What's the problem?

**Comment by donholly** [comment]
You could implement the logic found here:
https://gist.github.com/toblerpwn/5393460

Though you'll definitely want to make that optional and by default off.

**Comment by guyisra** [comment]
added a pr on #91
