### ISSUE TITLE
Why using "floorf" for calculating item width and height?

### ISSUE THREAD

**Issue by kevin0571** [chiahsien/CHTCollectionViewWaterfallLayout#88]
Hi,

In CHTCollectionViewWaterfallLayout.m, it uses "floorf" for calculating item width and height, but I didn't use "floorf" for calculating dynamic height in my collection view. Then it causes different results and shows incorrect UI.

**Comment by chiahsien** [comment]
Because decimal doesn't make sense for width and height.

**Comment by kevin0571** [comment]
@chiahsien But sometimes we do have to use 0.5 in width/height. 
It's fine for CHTCollectionViewWaterfallLayout to force using "floorf" width&height, but may be should provide a public method for calculating the width&height.
