### ISSUE TITLE
What is the purpose of unionRects?

### ISSUE THREAD

**Issue by guyisra** [chiahsien/CHTCollectionViewWaterfallLayout#90]
I am trying to add floating headers, and I don't understand what is the purpose of unionRects..

When adding to it 
```
 // Build union rects
  idx = 0;
  NSInteger itemCounts = [self.allItemAttributes count];
  while (idx < itemCounts) {
    CGRect rect1 = ((UICollectionViewLayoutAttributes *)self.allItemAttributes[idx]).frame;
    idx = MIN(idx + unionSize, itemCounts) - 1;
    CGRect rect2 = ((UICollectionViewLayoutAttributes *)self.allItemAttributes[idx]).frame;
    [self.unionRects addObject:[NSValue valueWithCGRect:CGRectUnion(rect1, rect2)]];
    idx++;
  }
```
So this goes over all attributes and makes a union of their frames' rects.. I don't understand why and how this is used in this way.
Why is unionSize 20? 

I saw this 
```
Build union rects — these are used to calculate which cells are currently visible later in -layoutAttributesForElementsInRect:
```
on http://www.rahuljiresal.com/2014/03/understanding-chtcollectionviewwaterfalllayout/

Once I understand I might be able to understand layoutAttributesForElementsInRect:rect  since the attributes that are being processed depend on 
```
  for (i = 0; i < self.unionRects.count; i++) {
    if (CGRectIntersectsRect(rect, [self.unionRects[i] CGRectValue])) {
      begin = i * unionSize;
      break;
    }
  }
  for (i = self.unionRects.count - 1; i >= 0; i--) {
    if (CGRectIntersectsRect(rect, [self.unionRects[i] CGRectValue])) {
      end = MIN((i + 1) * unionSize, self.allItemAttributes.count);
      break;
    }
  }
  for (i = begin; i < end; i++) {
    UICollectionViewLayoutAttributes *attr = self.allItemAttributes[i];
    if (CGRectIntersectsRect(rect, attr.frame)) {
      [attrs addObject:attr];
    }
  }
```

So, an item that isn't between begin and end doesn't get processed, but what defines them is unionSize which is, as I see it, arbitrarily 20

setting 
```
 begin = 0;
 end = self.allItemAttributes.count;
```
works, but I guess that its not very efficient, so finding begin and end is a way to work only on the visible items in the layout. Which, if that is correct, its a problem for doing floating headers since the itemAttribute that represents the header will not always be in the begin-end segment, yet its frame is visible

So I guess to find the correct header/footer that is relevant I need to know what section it is and add that section's header and footer separately. 

Thanks

**Comment by chiahsien** [comment]
Sorry to reply late.

`unionRects` are blocks of cell rects.
In `layoutAttributesForElementsInRect:rect`, it would take a long time if we enumerate from the first cell rect to the last one. But it would be 20 times faster if we enumerate the `unionRects`.

Hope this help.

**Comment by sdlbp** [comment]
@chiahsien 

Your handling of this piece is very clever. I would like a deeper understanding or refine the idea of ​​this piece, but do not know how to describe this piece of thought with a more professional terminology, so to ask you how to use a more professional terms to describe this algorithm, so I understand more knowledge. Thank you

**Comment by chiahsien** [comment]
I think it's kind of a tree.
