### ISSUE TITLE
Update cocoapods

### ISSUE THREAD

**Issue by flagoworld** [chiahsien/CHTCollectionViewWaterfallLayout#96]
I think cocoapods needs to be updated and the version incremented. You merged in my minimumContentHeight, I ran "pod install", and it installed an older version without minimumContentHeight.

**Comment by chiahsien** [comment]
I'll do it but I don't know when.
For now, you can modify your podfile to this
```
pod 'CHTCollectionViewWaterfallLayout', :git => 'https://github.com/chiahsien/CHTCollectionViewWaterfallLayout.git', :branch => 'develop'
```
