### ISSUE TITLE
Dynamic Sizing of Header

### ISSUE THREAD

**Issue by pushtheworldllc** [chiahsien/CHTCollectionViewWaterfallLayout#97]
I am using your layout (fantastic job) however I seem to run into an issue where I want to set the height for the header at runtime. However all your examples show a static size. Is it possible to configure height dynamically at runtime?

**Comment by chiahsien** [comment]
You can implement the `- (CGFloat)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout heightForHeaderInSection:(NSInteger)section;` method in your delegate.

**Comment by pushtheworldllc** [comment]
Yes my apologies, thank you for pointing that out. So happy to have gotten that working!

**Comment by VetrivelMobile** [comment]
Hi, Thanks for your file, But i ahving an issue to implementing this,

The issue was saying that CHTCollectionViewDelegateWaterfallLayout decalring in my controller.h file,

can you please help me on this

**Comment by moses1990** [comment]
How do i implement sticky headers using your class ?

Please help

**Comment by kevinliu23** [comment]
Any way to implement sticky header using the CHTCollectionViewWaterfallLayout library?

**Comment by kevinliu23** [comment]
@chiahsien What I mean by sticky headers is when you scroll, the header stays at the top. Like what this library is doing: https://github.com/CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout

I'm using and loving the library you've created, and was hoping I can enable sticky header using it. Thanks for your amazing work Nelson!

**Comment by asifbilal786** [comment]
@chiahsien , please add the sticky header feature in your library. That would be really useful.
